// Code generated by scripts/codegen/go.ts; DO NOT EDIT.
// Source: api.schema.json

package rpc

import (
	"encoding/json"
	"errors"
)

func unmarshalAgentRegistrySpawnResult(data []byte) (AgentRegistrySpawnResult, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case AgentRegistrySpawnResultKindRegistryTimeout:
		var d AgentRegistrySpawnRegistryTimeout
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AgentRegistrySpawnResultKindSpawnError:
		var d AgentRegistrySpawnError
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AgentRegistrySpawnResultKindSpawned:
		var d AgentRegistrySpawnSpawned
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AgentRegistrySpawnResultKindValidationError:
		var d AgentRegistrySpawnValidationError
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawAgentRegistrySpawnResultData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawAgentRegistrySpawnResultData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r AgentRegistrySpawnError) MarshalJSON() ([]byte, error) {
	type alias AgentRegistrySpawnError
	return json.Marshal(struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r AgentRegistrySpawnRegistryTimeout) MarshalJSON() ([]byte, error) {
	type alias AgentRegistrySpawnRegistryTimeout
	return json.Marshal(struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r AgentRegistrySpawnSpawned) MarshalJSON() ([]byte, error) {
	type alias AgentRegistrySpawnSpawned
	return json.Marshal(struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r AgentRegistrySpawnValidationError) MarshalJSON() ([]byte, error) {
	type alias AgentRegistrySpawnValidationError
	return json.Marshal(struct {
		Kind AgentRegistrySpawnResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func unmarshalAttachment(data []byte) (Attachment, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type AttachmentType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case AttachmentTypeBlob:
		var d AttachmentBlob
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AttachmentTypeDirectory:
		var d AttachmentDirectory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AttachmentTypeExtensionContext:
		var d AttachmentExtensionContext
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AttachmentTypeFile:
		var d AttachmentFile
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AttachmentTypeGitHubReference:
		var d AttachmentGitHubReference
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AttachmentTypeSelection:
		var d AttachmentSelection
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawAttachmentData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawAttachmentData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r AttachmentBlob) MarshalJSON() ([]byte, error) {
	type alias AttachmentBlob
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r AttachmentDirectory) MarshalJSON() ([]byte, error) {
	type alias AttachmentDirectory
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r AttachmentExtensionContext) MarshalJSON() ([]byte, error) {
	type alias AttachmentExtensionContext
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r AttachmentFile) MarshalJSON() ([]byte, error) {
	type alias AttachmentFile
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r AttachmentGitHubReference) MarshalJSON() ([]byte, error) {
	type alias AttachmentGitHubReference
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r AttachmentSelection) MarshalJSON() ([]byte, error) {
	type alias AttachmentSelection
	return json.Marshal(struct {
		Type AttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func unmarshalAuthInfo(data []byte) (AuthInfo, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type AuthInfoType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case AuthInfoTypeAPIKey:
		var d APIKeyAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeCopilotAPIToken:
		var d CopilotAPITokenAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeEnv:
		var d EnvAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeGhCLI:
		var d GhCLIAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeHMAC:
		var d HMACAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeToken:
		var d TokenAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case AuthInfoTypeUser:
		var d UserAuthInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawAuthInfoData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawAuthInfoData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r APIKeyAuthInfo) MarshalJSON() ([]byte, error) {
	type alias APIKeyAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r CopilotAPITokenAuthInfo) MarshalJSON() ([]byte, error) {
	type alias CopilotAPITokenAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r EnvAuthInfo) MarshalJSON() ([]byte, error) {
	type alias EnvAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r GhCLIAuthInfo) MarshalJSON() ([]byte, error) {
	type alias GhCLIAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r HMACAuthInfo) MarshalJSON() ([]byte, error) {
	type alias HMACAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r TokenAuthInfo) MarshalJSON() ([]byte, error) {
	type alias TokenAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UserAuthInfo) MarshalJSON() ([]byte, error) {
	type alias UserAuthInfo
	return json.Marshal(struct {
		Type AuthInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func unmarshalQueuedCommandResult(data []byte) (QueuedCommandResult, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Handled *bool `json:"handled"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if raw.Handled == nil {
		return nil, errors.New("data did not match any union variant for QueuedCommandResult")
	}

	switch *raw.Handled {
	case false:
		var d QueuedCommandNotHandled
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case true:
		var d QueuedCommandHandled
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	return nil, errors.New("data did not match any union variant for QueuedCommandResult")
}

func (r QueuedCommandHandled) MarshalJSON() ([]byte, error) {
	type alias QueuedCommandHandled
	return json.Marshal(struct {
		Handled bool `json:"handled"`
		alias
	}{
		Handled: r.Handled(),
		alias:   alias(r),
	})
}

func (r QueuedCommandNotHandled) MarshalJSON() ([]byte, error) {
	type alias QueuedCommandNotHandled
	return json.Marshal(struct {
		Handled bool `json:"handled"`
		alias
	}{
		Handled: r.Handled(),
		alias:   alias(r),
	})
}

func (r *CommandsRespondToQueuedCommandRequest) UnmarshalJSON(data []byte) error {
	type rawCommandsRespondToQueuedCommandRequest struct {
		RequestID string          `json:"requestId"`
		Result    json.RawMessage `json:"result"`
	}
	var raw rawCommandsRespondToQueuedCommandRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.RequestID = raw.RequestID
	if raw.Result != nil {
		value, err := unmarshalQueuedCommandResult(raw.Result)
		if err != nil {
			return err
		}
		r.Result = value
	}
	return nil
}

func (r EventLogTypes) MarshalJSON() ([]byte, error) {
	if r.String != nil {
		return json.Marshal(r.String)
	}
	if r.StringArray != nil {
		return json.Marshal(r.StringArray)
	}
	return []byte("null"), nil
}

func (r *EventLogTypes) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*r = EventLogTypes{}
		return nil
	}
	{
		var value EventLogTypesString
		if err := json.Unmarshal(data, &value); err == nil {
			*r = EventLogTypes{String: &value}
			return nil
		}
	}
	{
		var value []string
		if err := json.Unmarshal(data, &value); err == nil {
			*r = EventLogTypes{StringArray: value}
			return nil
		}
	}
	return errors.New("data did not match any union variant for EventLogTypes")
}

func unmarshalExternalToolTextResultForLlmContent(data []byte) (ExternalToolTextResultForLlmContent, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case ExternalToolTextResultForLlmContentTypeAudio:
		var d ExternalToolTextResultForLlmContentAudio
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case ExternalToolTextResultForLlmContentTypeImage:
		var d ExternalToolTextResultForLlmContentImage
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case ExternalToolTextResultForLlmContentTypeResource:
		var d ExternalToolTextResultForLlmContentResource
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case ExternalToolTextResultForLlmContentTypeResourceLink:
		var d ExternalToolTextResultForLlmContentResourceLink
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case ExternalToolTextResultForLlmContentTypeTerminal:
		var d ExternalToolTextResultForLlmContentTerminal
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case ExternalToolTextResultForLlmContentTypeText:
		var d ExternalToolTextResultForLlmContentText
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawExternalToolTextResultForLlmContentData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawExternalToolTextResultForLlmContentData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r ExternalToolTextResultForLlmContentAudio) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentAudio
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r ExternalToolTextResultForLlmContentImage) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentImage
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func matchesEmbeddedBlobResourceContents(data []byte) bool {
	var rawGroup0 struct {
		Blob json.RawMessage `json:"blob"`
		Text json.RawMessage `json:"text"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Blob == nil {
		return false
	}
	return rawGroup0.Text == nil
}

func matchesEmbeddedTextResourceContents(data []byte) bool {
	var rawGroup0 struct {
		Blob json.RawMessage `json:"blob"`
		Text json.RawMessage `json:"text"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Text == nil {
		return false
	}
	return rawGroup0.Blob == nil
}

func unmarshalExternalToolTextResultForLlmContentResourceDetails(data []byte) (ExternalToolTextResultForLlmContentResourceDetails, error) {
	if string(data) == "null" {
		return nil, nil
	}
	if matchesEmbeddedBlobResourceContents(data) {
		var d EmbeddedBlobResourceContents
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	if matchesEmbeddedTextResourceContents(data) {
		var d EmbeddedTextResourceContents
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	return &RawExternalToolTextResultForLlmContentResourceDetailsData{Raw: data}, nil
}

func (r RawExternalToolTextResultForLlmContentResourceDetailsData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return []byte("null"), nil
}

func (r *ExternalToolTextResultForLlmContentResource) UnmarshalJSON(data []byte) error {
	type rawExternalToolTextResultForLlmContentResource struct {
		Resource json.RawMessage `json:"resource"`
	}
	var raw rawExternalToolTextResultForLlmContentResource
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Resource != nil {
		value, err := unmarshalExternalToolTextResultForLlmContentResourceDetails(raw.Resource)
		if err != nil {
			return err
		}
		r.Resource = value
	}
	return nil
}

func (r ExternalToolTextResultForLlmContentResource) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentResource
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r ExternalToolTextResultForLlmContentResourceLink) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentResourceLink
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r ExternalToolTextResultForLlmContentTerminal) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentTerminal
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r ExternalToolTextResultForLlmContentText) MarshalJSON() ([]byte, error) {
	type alias ExternalToolTextResultForLlmContentText
	return json.Marshal(struct {
		Type ExternalToolTextResultForLlmContentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r *ExternalToolTextResultForLlm) UnmarshalJSON(data []byte) error {
	type rawExternalToolTextResultForLlm struct {
		BinaryResultsForLlm []ExternalToolTextResultForLlmBinaryResultsForLlm `json:"binaryResultsForLlm,omitzero"`
		Contents            []json.RawMessage                                 `json:"contents,omitzero"`
		Error               *string                                           `json:"error,omitempty"`
		ResultType          *string                                           `json:"resultType,omitempty"`
		SessionLog          *string                                           `json:"sessionLog,omitempty"`
		TextResultForLlm    string                                            `json:"textResultForLlm"`
		ToolTelemetry       map[string]any                                    `json:"toolTelemetry,omitzero"`
	}
	var raw rawExternalToolTextResultForLlm
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.BinaryResultsForLlm = raw.BinaryResultsForLlm
	if raw.Contents != nil {
		r.Contents = make([]ExternalToolTextResultForLlmContent, 0, len(raw.Contents))
		for _, rawItem := range raw.Contents {
			value, err := unmarshalExternalToolTextResultForLlmContent(rawItem)
			if err != nil {
				return err
			}
			r.Contents = append(r.Contents, value)
		}
	}
	r.Error = raw.Error
	r.ResultType = raw.ResultType
	r.SessionLog = raw.SessionLog
	r.TextResultForLlm = raw.TextResultForLlm
	r.ToolTelemetry = raw.ToolTelemetry
	return nil
}

func unmarshalExternalToolResult(data []byte) (ExternalToolResult, error) {
	if string(data) == "null" {
		return nil, nil
	}
	{
		var value string
		if err := json.Unmarshal(data, &value); err == nil {
			return ExternalToolStringResult(value), nil
		}
	}
	{
		var value ExternalToolTextResultForLlm
		if err := json.Unmarshal(data, &value); err == nil {
			return &value, nil
		}
	}
	return nil, errors.New("data did not match any union variant for ExternalToolResult")
}

func unmarshalFilterMapping(data []byte) (FilterMapping, error) {
	if string(data) == "null" {
		return nil, nil
	}
	{
		var value FilterMappingEnumMap
		if err := json.Unmarshal(data, &value); err == nil {
			return value, nil
		}
	}
	{
		var value ContentFilterMode
		if err := json.Unmarshal(data, &value); err == nil {
			return value, nil
		}
	}
	return nil, errors.New("data did not match any union variant for FilterMapping")
}

func (r *HandlePendingToolCallRequest) UnmarshalJSON(data []byte) error {
	type rawHandlePendingToolCallRequest struct {
		Error     *string         `json:"error,omitempty"`
		RequestID string          `json:"requestId"`
		Result    json.RawMessage `json:"result,omitempty"`
	}
	var raw rawHandlePendingToolCallRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.Error = raw.Error
	r.RequestID = raw.RequestID
	if raw.Result != nil {
		value, err := unmarshalExternalToolResult(raw.Result)
		if err != nil {
			return err
		}
		r.Result = value
	}
	return nil
}

func (r InstalledPluginSource) MarshalJSON() ([]byte, error) {
	if r.InstalledPluginSourceGitHub != nil {
		return json.Marshal(r.InstalledPluginSourceGitHub)
	}
	if r.InstalledPluginSourceLocal != nil {
		return json.Marshal(r.InstalledPluginSourceLocal)
	}
	if r.InstalledPluginSourceURL != nil {
		return json.Marshal(r.InstalledPluginSourceURL)
	}
	if r.String != nil {
		return json.Marshal(r.String)
	}
	return []byte("null"), nil
}

func (r *InstalledPluginSource) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*r = InstalledPluginSource{}
		return nil
	}
	{
		var value InstalledPluginSourceGitHub
		if err := json.Unmarshal(data, &value); err == nil {
			*r = InstalledPluginSource{InstalledPluginSourceGitHub: &value}
			return nil
		}
	}
	{
		var value InstalledPluginSourceLocal
		if err := json.Unmarshal(data, &value); err == nil {
			*r = InstalledPluginSource{InstalledPluginSourceLocal: &value}
			return nil
		}
	}
	{
		var value InstalledPluginSourceURL
		if err := json.Unmarshal(data, &value); err == nil {
			*r = InstalledPluginSource{InstalledPluginSourceURL: &value}
			return nil
		}
	}
	{
		var value string
		if err := json.Unmarshal(data, &value); err == nil {
			*r = InstalledPluginSource{String: &value}
			return nil
		}
	}
	return errors.New("data did not match any union variant for InstalledPluginSource")
}

func matchesMCPServerConfigHTTP(data []byte) bool {
	var rawGroup0 struct {
		Command json.RawMessage `json:"command"`
		URL     json.RawMessage `json:"url"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.URL == nil {
		return false
	}
	return rawGroup0.Command == nil
}

func matchesMCPServerConfigStdio(data []byte) bool {
	var rawGroup0 struct {
		Command json.RawMessage `json:"command"`
		URL     json.RawMessage `json:"url"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Command == nil {
		return false
	}
	return rawGroup0.URL == nil
}

func unmarshalMCPServerConfig(data []byte) (MCPServerConfig, error) {
	if string(data) == "null" {
		return nil, nil
	}
	if matchesMCPServerConfigHTTP(data) {
		var d MCPServerConfigHTTP
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	if matchesMCPServerConfigStdio(data) {
		var d MCPServerConfigStdio
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	return &RawMCPServerConfigData{Raw: data}, nil
}

func (r RawMCPServerConfigData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return []byte("null"), nil
}

func unmarshalMCPServerAuthConfig(data []byte) (MCPServerAuthConfig, error) {
	if string(data) == "null" {
		return nil, nil
	}
	{
		var value bool
		if err := json.Unmarshal(data, &value); err == nil {
			return MCPServerAuthConfigBoolean(value), nil
		}
	}
	{
		var value MCPServerAuthConfigRedirectPort
		if err := json.Unmarshal(data, &value); err == nil {
			return &value, nil
		}
	}
	return nil, errors.New("data did not match any union variant for MCPServerAuthConfig")
}

func (r *MCPServerConfigHTTP) UnmarshalJSON(data []byte) error {
	type rawMCPServerConfigHTTP struct {
		Auth              json.RawMessage                    `json:"auth,omitempty"`
		DeferTools        *MCPServerConfigDeferTools         `json:"deferTools,omitempty"`
		FilterMapping     json.RawMessage                    `json:"filterMapping,omitempty"`
		Headers           map[string]string                  `json:"headers,omitzero"`
		IsDefaultServer   *bool                              `json:"isDefaultServer,omitempty"`
		OauthClientID     *string                            `json:"oauthClientId,omitempty"`
		OauthGrantType    *MCPServerConfigHTTPOauthGrantType `json:"oauthGrantType,omitempty"`
		OauthPublicClient *bool                              `json:"oauthPublicClient,omitempty"`
		Oidc              json.RawMessage                    `json:"oidc,omitempty"`
		Timeout           *int64                             `json:"timeout,omitempty"`
		Tools             []string                           `json:"tools,omitzero"`
		Type              *MCPServerConfigHTTPType           `json:"type,omitempty"`
		URL               string                             `json:"url"`
	}
	var raw rawMCPServerConfigHTTP
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Auth != nil {
		value, err := unmarshalMCPServerAuthConfig(raw.Auth)
		if err != nil {
			return err
		}
		r.Auth = value
	}
	r.DeferTools = raw.DeferTools
	if raw.FilterMapping != nil {
		value, err := unmarshalFilterMapping(raw.FilterMapping)
		if err != nil {
			return err
		}
		r.FilterMapping = value
	}
	r.Headers = raw.Headers
	r.IsDefaultServer = raw.IsDefaultServer
	r.OauthClientID = raw.OauthClientID
	r.OauthGrantType = raw.OauthGrantType
	r.OauthPublicClient = raw.OauthPublicClient
	if raw.Oidc != nil {
		value, err := unmarshalMCPServerAuthConfig(raw.Oidc)
		if err != nil {
			return err
		}
		r.Oidc = value
	}
	r.Timeout = raw.Timeout
	r.Tools = raw.Tools
	r.Type = raw.Type
	r.URL = raw.URL
	return nil
}

func (r *MCPServerConfigStdio) UnmarshalJSON(data []byte) error {
	type rawMCPServerConfigStdio struct {
		Args            []string                   `json:"args,omitzero"`
		Auth            json.RawMessage            `json:"auth,omitempty"`
		Command         string                     `json:"command"`
		Cwd             *string                    `json:"cwd,omitempty"`
		DeferTools      *MCPServerConfigDeferTools `json:"deferTools,omitempty"`
		Env             map[string]string          `json:"env,omitzero"`
		FilterMapping   json.RawMessage            `json:"filterMapping,omitempty"`
		IsDefaultServer *bool                      `json:"isDefaultServer,omitempty"`
		Oidc            json.RawMessage            `json:"oidc,omitempty"`
		Timeout         *int64                     `json:"timeout,omitempty"`
		Tools           []string                   `json:"tools,omitzero"`
	}
	var raw rawMCPServerConfigStdio
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.Args = raw.Args
	if raw.Auth != nil {
		value, err := unmarshalMCPServerAuthConfig(raw.Auth)
		if err != nil {
			return err
		}
		r.Auth = value
	}
	r.Command = raw.Command
	r.Cwd = raw.Cwd
	r.DeferTools = raw.DeferTools
	r.Env = raw.Env
	if raw.FilterMapping != nil {
		value, err := unmarshalFilterMapping(raw.FilterMapping)
		if err != nil {
			return err
		}
		r.FilterMapping = value
	}
	r.IsDefaultServer = raw.IsDefaultServer
	if raw.Oidc != nil {
		value, err := unmarshalMCPServerAuthConfig(raw.Oidc)
		if err != nil {
			return err
		}
		r.Oidc = value
	}
	r.Timeout = raw.Timeout
	r.Tools = raw.Tools
	return nil
}

func (r *MCPConfigAddRequest) UnmarshalJSON(data []byte) error {
	type rawMCPConfigAddRequest struct {
		Config json.RawMessage `json:"config"`
		Name   string          `json:"name"`
	}
	var raw rawMCPConfigAddRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Config != nil {
		value, err := unmarshalMCPServerConfig(raw.Config)
		if err != nil {
			return err
		}
		r.Config = value
	}
	r.Name = raw.Name
	return nil
}

func (r *MCPConfigList) UnmarshalJSON(data []byte) error {
	type rawMCPConfigList struct {
		Servers map[string]json.RawMessage `json:"servers"`
	}
	var raw rawMCPConfigList
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Servers != nil {
		r.Servers = make(map[string]MCPServerConfig, len(raw.Servers))
		for key, rawValue := range raw.Servers {
			value, err := unmarshalMCPServerConfig(rawValue)
			if err != nil {
				return err
			}
			r.Servers[key] = value
		}
	}
	return nil
}

func (r *MCPConfigUpdateRequest) UnmarshalJSON(data []byte) error {
	type rawMCPConfigUpdateRequest struct {
		Config json.RawMessage `json:"config"`
		Name   string          `json:"name"`
	}
	var raw rawMCPConfigUpdateRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Config != nil {
		value, err := unmarshalMCPServerConfig(raw.Config)
		if err != nil {
			return err
		}
		r.Config = value
	}
	r.Name = raw.Name
	return nil
}

func unmarshalPermissionDecision(data []byte) (PermissionDecision, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind PermissionDecisionKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case PermissionDecisionKindApproveForLocation:
		var d PermissionDecisionApproveForLocation
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApproveForSession:
		var d PermissionDecisionApproveForSession
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApproveOnce:
		var d PermissionDecisionApproveOnce
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApprovePermanently:
		var d PermissionDecisionApprovePermanently
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApproved:
		var d PermissionDecisionApproved
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApprovedForLocation:
		var d PermissionDecisionApprovedForLocation
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindApprovedForSession:
		var d PermissionDecisionApprovedForSession
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindCancelled:
		var d PermissionDecisionCancelled
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindDeniedByContentExclusionPolicy:
		var d PermissionDecisionDeniedByContentExclusionPolicy
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindDeniedByPermissionRequestHook:
		var d PermissionDecisionDeniedByPermissionRequestHook
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindDeniedByRules:
		var d PermissionDecisionDeniedByRules
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindDeniedInteractivelyByUser:
		var d PermissionDecisionDeniedInteractivelyByUser
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindDeniedNoApprovalRuleAndCouldNotRequestFromUser:
		var d PermissionDecisionDeniedNoApprovalRuleAndCouldNotRequestFromUser
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindReject:
		var d PermissionDecisionReject
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionKindUserNotAvailable:
		var d PermissionDecisionUserNotAvailable
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawPermissionDecisionData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawPermissionDecisionData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r PermissionDecisionApproved) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproved
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func unmarshalUserToolSessionApproval(data []byte) (UserToolSessionApproval, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case UserToolSessionApprovalKindCommands:
		var d UserToolSessionApprovalCommands
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindCustomTool:
		var d UserToolSessionApprovalCustomTool
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindExtensionManagement:
		var d UserToolSessionApprovalExtensionManagement
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindExtensionPermissionAccess:
		var d UserToolSessionApprovalExtensionPermissionAccess
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindMCP:
		var d UserToolSessionApprovalMCP
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindMemory:
		var d UserToolSessionApprovalMemory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindRead:
		var d UserToolSessionApprovalRead
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UserToolSessionApprovalKindWrite:
		var d UserToolSessionApprovalWrite
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawUserToolSessionApprovalData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawUserToolSessionApprovalData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r UserToolSessionApprovalCommands) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalCommands
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalCustomTool) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalCustomTool
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalExtensionManagement) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalExtensionManagement
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalExtensionPermissionAccess) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalExtensionPermissionAccess
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalMCP) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalMCP
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalMemory) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalMemory
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalRead) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalRead
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r UserToolSessionApprovalWrite) MarshalJSON() ([]byte, error) {
	type alias UserToolSessionApprovalWrite
	return json.Marshal(struct {
		Kind UserToolSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionDecisionApprovedForLocation) UnmarshalJSON(data []byte) error {
	type rawPermissionDecisionApprovedForLocation struct {
		Approval    json.RawMessage `json:"approval"`
		LocationKey string          `json:"locationKey"`
	}
	var raw rawPermissionDecisionApprovedForLocation
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Approval != nil {
		value, err := unmarshalUserToolSessionApproval(raw.Approval)
		if err != nil {
			return err
		}
		r.Approval = value
	}
	r.LocationKey = raw.LocationKey
	return nil
}

func (r PermissionDecisionApprovedForLocation) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApprovedForLocation
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionDecisionApprovedForSession) UnmarshalJSON(data []byte) error {
	type rawPermissionDecisionApprovedForSession struct {
		Approval json.RawMessage `json:"approval"`
	}
	var raw rawPermissionDecisionApprovedForSession
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Approval != nil {
		value, err := unmarshalUserToolSessionApproval(raw.Approval)
		if err != nil {
			return err
		}
		r.Approval = value
	}
	return nil
}

func (r PermissionDecisionApprovedForSession) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApprovedForSession
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func unmarshalPermissionDecisionApproveForLocationApproval(data []byte) (PermissionDecisionApproveForLocationApproval, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case PermissionDecisionApproveForLocationApprovalKindCommands:
		var d PermissionDecisionApproveForLocationApprovalCommands
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindCustomTool:
		var d PermissionDecisionApproveForLocationApprovalCustomTool
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindExtensionManagement:
		var d PermissionDecisionApproveForLocationApprovalExtensionManagement
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindExtensionPermissionAccess:
		var d PermissionDecisionApproveForLocationApprovalExtensionPermissionAccess
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindMCP:
		var d PermissionDecisionApproveForLocationApprovalMCP
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindMCPSampling:
		var d PermissionDecisionApproveForLocationApprovalMCPSampling
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindMemory:
		var d PermissionDecisionApproveForLocationApprovalMemory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindRead:
		var d PermissionDecisionApproveForLocationApprovalRead
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForLocationApprovalKindWrite:
		var d PermissionDecisionApproveForLocationApprovalWrite
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawPermissionDecisionApproveForLocationApprovalData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawPermissionDecisionApproveForLocationApprovalData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r PermissionDecisionApproveForLocationApprovalCommands) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalCommands
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalCustomTool) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalCustomTool
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalExtensionManagement) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalExtensionManagement
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalExtensionPermissionAccess) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalExtensionPermissionAccess
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalMCP) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalMCP
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalMCPSampling) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalMCPSampling
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalMemory) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalMemory
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalRead) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalRead
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForLocationApprovalWrite) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocationApprovalWrite
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForLocationApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionDecisionApproveForLocation) UnmarshalJSON(data []byte) error {
	type rawPermissionDecisionApproveForLocation struct {
		Approval    json.RawMessage `json:"approval"`
		LocationKey string          `json:"locationKey"`
	}
	var raw rawPermissionDecisionApproveForLocation
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Approval != nil {
		value, err := unmarshalPermissionDecisionApproveForLocationApproval(raw.Approval)
		if err != nil {
			return err
		}
		r.Approval = value
	}
	r.LocationKey = raw.LocationKey
	return nil
}

func (r PermissionDecisionApproveForLocation) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForLocation
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func unmarshalPermissionDecisionApproveForSessionApproval(data []byte) (PermissionDecisionApproveForSessionApproval, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case PermissionDecisionApproveForSessionApprovalKindCommands:
		var d PermissionDecisionApproveForSessionApprovalCommands
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindCustomTool:
		var d PermissionDecisionApproveForSessionApprovalCustomTool
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindExtensionManagement:
		var d PermissionDecisionApproveForSessionApprovalExtensionManagement
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindExtensionPermissionAccess:
		var d PermissionDecisionApproveForSessionApprovalExtensionPermissionAccess
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindMCP:
		var d PermissionDecisionApproveForSessionApprovalMCP
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindMCPSampling:
		var d PermissionDecisionApproveForSessionApprovalMCPSampling
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindMemory:
		var d PermissionDecisionApproveForSessionApprovalMemory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindRead:
		var d PermissionDecisionApproveForSessionApprovalRead
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionDecisionApproveForSessionApprovalKindWrite:
		var d PermissionDecisionApproveForSessionApprovalWrite
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawPermissionDecisionApproveForSessionApprovalData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawPermissionDecisionApproveForSessionApprovalData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r PermissionDecisionApproveForSessionApprovalCommands) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalCommands
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalCustomTool) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalCustomTool
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalExtensionManagement) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalExtensionManagement
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalExtensionPermissionAccess) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalExtensionPermissionAccess
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalMCP) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalMCP
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalMCPSampling) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalMCPSampling
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalMemory) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalMemory
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalRead) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalRead
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveForSessionApprovalWrite) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSessionApprovalWrite
	return json.Marshal(struct {
		Kind PermissionDecisionApproveForSessionApprovalKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionDecisionApproveForSession) UnmarshalJSON(data []byte) error {
	type rawPermissionDecisionApproveForSession struct {
		Approval json.RawMessage `json:"approval,omitempty"`
		Domain   *string         `json:"domain,omitempty"`
	}
	var raw rawPermissionDecisionApproveForSession
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Approval != nil {
		value, err := unmarshalPermissionDecisionApproveForSessionApproval(raw.Approval)
		if err != nil {
			return err
		}
		r.Approval = value
	}
	r.Domain = raw.Domain
	return nil
}

func (r PermissionDecisionApproveForSession) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveForSession
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApproveOnce) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApproveOnce
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionApprovePermanently) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionApprovePermanently
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionCancelled) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionCancelled
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionDeniedByContentExclusionPolicy) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionDeniedByContentExclusionPolicy
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionDeniedByPermissionRequestHook) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionDeniedByPermissionRequestHook
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionDeniedByRules) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionDeniedByRules
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionDeniedInteractivelyByUser) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionDeniedInteractivelyByUser
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionDeniedNoApprovalRuleAndCouldNotRequestFromUser) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionDeniedNoApprovalRuleAndCouldNotRequestFromUser
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionReject) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionReject
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionDecisionUserNotAvailable) MarshalJSON() ([]byte, error) {
	type alias PermissionDecisionUserNotAvailable
	return json.Marshal(struct {
		Kind PermissionDecisionKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionDecisionRequest) UnmarshalJSON(data []byte) error {
	type rawPermissionDecisionRequest struct {
		RequestID string          `json:"requestId"`
		Result    json.RawMessage `json:"result"`
	}
	var raw rawPermissionDecisionRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.RequestID = raw.RequestID
	if raw.Result != nil {
		value, err := unmarshalPermissionDecision(raw.Result)
		if err != nil {
			return err
		}
		r.Result = value
	}
	return nil
}

func unmarshalPermissionsLocationsAddToolApprovalDetails(data []byte) (PermissionsLocationsAddToolApprovalDetails, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case PermissionsLocationsAddToolApprovalDetailsKindCommands:
		var d PermissionsLocationsAddToolApprovalDetailsCommands
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindCustomTool:
		var d PermissionsLocationsAddToolApprovalDetailsCustomTool
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindExtensionManagement:
		var d PermissionsLocationsAddToolApprovalDetailsExtensionManagement
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindExtensionPermissionAccess:
		var d PermissionsLocationsAddToolApprovalDetailsExtensionPermissionAccess
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindMCP:
		var d PermissionsLocationsAddToolApprovalDetailsMCP
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindMCPSampling:
		var d PermissionsLocationsAddToolApprovalDetailsMCPSampling
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindMemory:
		var d PermissionsLocationsAddToolApprovalDetailsMemory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindRead:
		var d PermissionsLocationsAddToolApprovalDetailsRead
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PermissionsLocationsAddToolApprovalDetailsKindWrite:
		var d PermissionsLocationsAddToolApprovalDetailsWrite
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawPermissionsLocationsAddToolApprovalDetailsData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawPermissionsLocationsAddToolApprovalDetailsData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsCommands) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsCommands
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsCustomTool) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsCustomTool
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsExtensionManagement) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsExtensionManagement
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsExtensionPermissionAccess) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsExtensionPermissionAccess
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsMCP) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsMCP
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsMCPSampling) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsMCPSampling
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsMemory) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsMemory
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsRead) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsRead
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r PermissionsLocationsAddToolApprovalDetailsWrite) MarshalJSON() ([]byte, error) {
	type alias PermissionsLocationsAddToolApprovalDetailsWrite
	return json.Marshal(struct {
		Kind PermissionsLocationsAddToolApprovalDetailsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *PermissionLocationAddToolApprovalParams) UnmarshalJSON(data []byte) error {
	type rawPermissionLocationAddToolApprovalParams struct {
		Approval    json.RawMessage `json:"approval"`
		LocationKey string          `json:"locationKey"`
	}
	var raw rawPermissionLocationAddToolApprovalParams
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Approval != nil {
		value, err := unmarshalPermissionsLocationsAddToolApprovalDetails(raw.Approval)
		if err != nil {
			return err
		}
		r.Approval = value
	}
	r.LocationKey = raw.LocationKey
	return nil
}

func unmarshalPushAttachment(data []byte) (PushAttachment, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type PushAttachmentType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case PushAttachmentTypeBlob:
		var d PushAttachmentBlob
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PushAttachmentTypeDirectory:
		var d PushAttachmentDirectory
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PushAttachmentTypeExtensionContext:
		var d ExtensionContextPushInput
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PushAttachmentTypeFile:
		var d PushAttachmentFile
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PushAttachmentTypeGitHubReference:
		var d PushAttachmentGitHubReference
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case PushAttachmentTypeSelection:
		var d PushAttachmentSelection
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawPushAttachmentData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawPushAttachmentData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r ExtensionContextPushInput) MarshalJSON() ([]byte, error) {
	type alias ExtensionContextPushInput
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r PushAttachmentBlob) MarshalJSON() ([]byte, error) {
	type alias PushAttachmentBlob
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r PushAttachmentDirectory) MarshalJSON() ([]byte, error) {
	type alias PushAttachmentDirectory
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r PushAttachmentFile) MarshalJSON() ([]byte, error) {
	type alias PushAttachmentFile
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r PushAttachmentGitHubReference) MarshalJSON() ([]byte, error) {
	type alias PushAttachmentGitHubReference
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r PushAttachmentSelection) MarshalJSON() ([]byte, error) {
	type alias PushAttachmentSelection
	return json.Marshal(struct {
		Type PushAttachmentType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func unmarshalRemoteControlStatus(data []byte) (RemoteControlStatus, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		State RemoteControlStatusState `json:"state"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.State {
	case RemoteControlStatusStateActive:
		var d RemoteControlStatusActive
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case RemoteControlStatusStateConnecting:
		var d RemoteControlStatusConnecting
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case RemoteControlStatusStateError:
		var d RemoteControlStatusError
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case RemoteControlStatusStateOff:
		var d RemoteControlStatusOff
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawRemoteControlStatusData{Discriminator: raw.State, Raw: data}, nil
	}
}

func (r RawRemoteControlStatusData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		State RemoteControlStatusState `json:"state"`
	}{
		State: r.Discriminator,
	})
}

func (r RemoteControlStatusActive) MarshalJSON() ([]byte, error) {
	type alias RemoteControlStatusActive
	return json.Marshal(struct {
		State RemoteControlStatusState `json:"state"`
		alias
	}{
		State: r.State(),
		alias: alias(r),
	})
}

func (r RemoteControlStatusConnecting) MarshalJSON() ([]byte, error) {
	type alias RemoteControlStatusConnecting
	return json.Marshal(struct {
		State RemoteControlStatusState `json:"state"`
		alias
	}{
		State: r.State(),
		alias: alias(r),
	})
}

func (r RemoteControlStatusError) MarshalJSON() ([]byte, error) {
	type alias RemoteControlStatusError
	return json.Marshal(struct {
		State RemoteControlStatusState `json:"state"`
		alias
	}{
		State: r.State(),
		alias: alias(r),
	})
}

func (r RemoteControlStatusOff) MarshalJSON() ([]byte, error) {
	type alias RemoteControlStatusOff
	return json.Marshal(struct {
		State RemoteControlStatusState `json:"state"`
		alias
	}{
		State: r.State(),
		alias: alias(r),
	})
}

func (r *RemoteControlStatusResult) UnmarshalJSON(data []byte) error {
	type rawRemoteControlStatusResult struct {
		Status json.RawMessage `json:"status"`
	}
	var raw rawRemoteControlStatusResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Status != nil {
		value, err := unmarshalRemoteControlStatus(raw.Status)
		if err != nil {
			return err
		}
		r.Status = value
	}
	return nil
}

func (r *RemoteControlStopResult) UnmarshalJSON(data []byte) error {
	type rawRemoteControlStopResult struct {
		Status  json.RawMessage `json:"status"`
		Stopped bool            `json:"stopped"`
	}
	var raw rawRemoteControlStopResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Status != nil {
		value, err := unmarshalRemoteControlStatus(raw.Status)
		if err != nil {
			return err
		}
		r.Status = value
	}
	r.Stopped = raw.Stopped
	return nil
}

func (r *RemoteControlTransferResult) UnmarshalJSON(data []byte) error {
	type rawRemoteControlTransferResult struct {
		Status      json.RawMessage `json:"status"`
		Transferred bool            `json:"transferred"`
	}
	var raw rawRemoteControlTransferResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Status != nil {
		value, err := unmarshalRemoteControlStatus(raw.Status)
		if err != nil {
			return err
		}
		r.Status = value
	}
	r.Transferred = raw.Transferred
	return nil
}

func (r *SendAttachmentsToMessageParams) UnmarshalJSON(data []byte) error {
	type rawSendAttachmentsToMessageParams struct {
		Attachments []json.RawMessage `json:"attachments"`
		InstanceID  *string           `json:"instanceId,omitempty"`
	}
	var raw rawSendAttachmentsToMessageParams
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Attachments != nil {
		r.Attachments = make([]PushAttachment, 0, len(raw.Attachments))
		for _, rawItem := range raw.Attachments {
			value, err := unmarshalPushAttachment(rawItem)
			if err != nil {
				return err
			}
			r.Attachments = append(r.Attachments, value)
		}
	}
	r.InstanceID = raw.InstanceID
	return nil
}

func (r *SendRequest) UnmarshalJSON(data []byte) error {
	type rawSendRequest struct {
		AgentMode      *SendAgentMode    `json:"agentMode,omitempty"`
		Attachments    []json.RawMessage `json:"attachments,omitzero"`
		Billable       *bool             `json:"billable,omitempty"`
		DisplayPrompt  *string           `json:"displayPrompt,omitempty"`
		Mode           *SendMode         `json:"mode,omitempty"`
		Prepend        *bool             `json:"prepend,omitempty"`
		Prompt         string            `json:"prompt"`
		RequestHeaders map[string]string `json:"requestHeaders,omitzero"`
		RequiredTool   *string           `json:"requiredTool,omitempty"`
		Source         *string           `json:"source,omitempty"`
		Traceparent    *string           `json:"traceparent,omitempty"`
		Tracestate     *string           `json:"tracestate,omitempty"`
		Wait           *bool             `json:"wait,omitempty"`
	}
	var raw rawSendRequest
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.AgentMode = raw.AgentMode
	if raw.Attachments != nil {
		r.Attachments = make([]Attachment, 0, len(raw.Attachments))
		for _, rawItem := range raw.Attachments {
			value, err := unmarshalAttachment(rawItem)
			if err != nil {
				return err
			}
			r.Attachments = append(r.Attachments, value)
		}
	}
	r.Billable = raw.Billable
	r.DisplayPrompt = raw.DisplayPrompt
	r.Mode = raw.Mode
	r.Prepend = raw.Prepend
	r.Prompt = raw.Prompt
	r.RequestHeaders = raw.RequestHeaders
	r.RequiredTool = raw.RequiredTool
	r.Source = raw.Source
	r.Traceparent = raw.Traceparent
	r.Tracestate = raw.Tracestate
	r.Wait = raw.Wait
	return nil
}

func (r SessionInstalledPluginSource) MarshalJSON() ([]byte, error) {
	if r.SessionInstalledPluginSourceGitHub != nil {
		return json.Marshal(r.SessionInstalledPluginSourceGitHub)
	}
	if r.SessionInstalledPluginSourceLocal != nil {
		return json.Marshal(r.SessionInstalledPluginSourceLocal)
	}
	if r.SessionInstalledPluginSourceURL != nil {
		return json.Marshal(r.SessionInstalledPluginSourceURL)
	}
	if r.String != nil {
		return json.Marshal(r.String)
	}
	return []byte("null"), nil
}

func (r *SessionInstalledPluginSource) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*r = SessionInstalledPluginSource{}
		return nil
	}
	{
		var value SessionInstalledPluginSourceGitHub
		if err := json.Unmarshal(data, &value); err == nil {
			*r = SessionInstalledPluginSource{SessionInstalledPluginSourceGitHub: &value}
			return nil
		}
	}
	{
		var value SessionInstalledPluginSourceLocal
		if err := json.Unmarshal(data, &value); err == nil {
			*r = SessionInstalledPluginSource{SessionInstalledPluginSourceLocal: &value}
			return nil
		}
	}
	{
		var value SessionInstalledPluginSourceURL
		if err := json.Unmarshal(data, &value); err == nil {
			*r = SessionInstalledPluginSource{SessionInstalledPluginSourceURL: &value}
			return nil
		}
	}
	{
		var value string
		if err := json.Unmarshal(data, &value); err == nil {
			*r = SessionInstalledPluginSource{String: &value}
			return nil
		}
	}
	return errors.New("data did not match any union variant for SessionInstalledPluginSource")
}

func unmarshalSessionListEntry(data []byte) (SessionListEntry, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		IsRemote *bool `json:"isRemote"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if raw.IsRemote == nil {
		return nil, errors.New("data did not match any union variant for SessionListEntry")
	}

	switch *raw.IsRemote {
	case false:
		var d LocalSessionMetadataValue
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case true:
		var d RemoteSessionMetadataValue
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	}
	return nil, errors.New("data did not match any union variant for SessionListEntry")
}

func (r LocalSessionMetadataValue) MarshalJSON() ([]byte, error) {
	type alias LocalSessionMetadataValue
	return json.Marshal(struct {
		IsRemote bool `json:"isRemote"`
		alias
	}{
		IsRemote: r.sessionListEntryIsRemote(),
		alias:    alias(r),
	})
}

func (r RemoteSessionMetadataValue) MarshalJSON() ([]byte, error) {
	type alias RemoteSessionMetadataValue
	return json.Marshal(struct {
		IsRemote bool `json:"isRemote"`
		alias
	}{
		IsRemote: r.sessionListEntryIsRemote(),
		alias:    alias(r),
	})
}

func (r *SessionList) UnmarshalJSON(data []byte) error {
	type rawSessionList struct {
		Sessions []json.RawMessage `json:"sessions"`
	}
	var raw rawSessionList
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Sessions != nil {
		r.Sessions = make([]SessionListEntry, 0, len(raw.Sessions))
		for _, rawItem := range raw.Sessions {
			value, err := unmarshalSessionListEntry(rawItem)
			if err != nil {
				return err
			}
			r.Sessions = append(r.Sessions, value)
		}
	}
	return nil
}

func (r *SessionOpenOptions) UnmarshalJSON(data []byte) error {
	type rawSessionOpenOptions struct {
		AdditionalContentExclusionPolicies     []SessionOpenOptionsAdditionalContentExclusionPolicy `json:"additionalContentExclusionPolicies,omitzero"`
		AgentContext                           *string                                              `json:"agentContext,omitempty"`
		AskUserDisabled                        *bool                                                `json:"askUserDisabled,omitempty"`
		AuthInfo                               json.RawMessage                                      `json:"authInfo,omitempty"`
		AvailableTools                         []string                                             `json:"availableTools,omitzero"`
		ClientKind                             *string                                              `json:"clientKind,omitempty"`
		ClientName                             *string                                              `json:"clientName,omitempty"`
		CoauthorEnabled                        *bool                                                `json:"coauthorEnabled,omitempty"`
		ConfigDir                              *string                                              `json:"configDir,omitempty"`
		ContinueOnAutoMode                     *bool                                                `json:"continueOnAutoMode,omitempty"`
		CopilotURL                             *string                                              `json:"copilotUrl,omitempty"`
		CustomAgentsLocalOnly                  *bool                                                `json:"customAgentsLocalOnly,omitempty"`
		DetachedFromSpawningParentEngagementID *string                                              `json:"detachedFromSpawningParentEngagementId,omitempty"`
		DetachedFromSpawningParentSessionID    *string                                              `json:"detachedFromSpawningParentSessionId,omitempty"`
		DisabledInstructionSources             []string                                             `json:"disabledInstructionSources,omitzero"`
		DisabledSkills                         []string                                             `json:"disabledSkills,omitzero"`
		EnableOnDemandInstructionDiscovery     *bool                                                `json:"enableOnDemandInstructionDiscovery,omitempty"`
		EnableScriptSafety                     *bool                                                `json:"enableScriptSafety,omitempty"`
		EnableStreaming                        *bool                                                `json:"enableStreaming,omitempty"`
		EnvValueMode                           *SessionOpenOptionsEnvValueMode                      `json:"envValueMode,omitempty"`
		EventsLogDirectory                     *string                                              `json:"eventsLogDirectory,omitempty"`
		ExcludedTools                          []string                                             `json:"excludedTools,omitzero"`
		ExpAssignments                         any                                                  `json:"expAssignments,omitempty"`
		FeatureFlags                           map[string]bool                                      `json:"featureFlags,omitzero"`
		InstalledPlugins                       []InstalledPlugin                                    `json:"installedPlugins,omitzero"`
		IntegrationID                          *string                                              `json:"integrationId,omitempty"`
		IsExperimentalMode                     *bool                                                `json:"isExperimentalMode,omitempty"`
		LogInteractiveShells                   *bool                                                `json:"logInteractiveShells,omitempty"`
		LspClientName                          *string                                              `json:"lspClientName,omitempty"`
		MaxInlineBinaryBytes                   *int64                                               `json:"maxInlineBinaryBytes,omitempty"`
		Memory                                 *MemoryConfiguration                                 `json:"memory,omitempty"`
		Model                                  *string                                              `json:"model,omitempty"`
		ModelCapabilitiesOverrides             *ModelCapabilitiesOverride                           `json:"modelCapabilitiesOverrides,omitempty"`
		Models                                 []ProviderModelConfig                                `json:"models,omitzero"`
		Name                                   *string                                              `json:"name,omitempty"`
		Provider                               *ProviderConfig                                      `json:"provider,omitempty"`
		Providers                              []NamedProviderConfig                                `json:"providers,omitzero"`
		ReasoningEffort                        *string                                              `json:"reasoningEffort,omitempty"`
		ReasoningSummary                       *SessionOpenOptionsReasoningSummary                  `json:"reasoningSummary,omitempty"`
		RemoteDefaultedOn                      *bool                                                `json:"remoteDefaultedOn,omitempty"`
		RemoteExporting                        *bool                                                `json:"remoteExporting,omitempty"`
		RemoteSteerable                        *bool                                                `json:"remoteSteerable,omitempty"`
		RunningInInteractiveMode               *bool                                                `json:"runningInInteractiveMode,omitempty"`
		SandboxConfig                          *SandboxConfig                                       `json:"sandboxConfig,omitempty"`
		SessionCapabilities                    []SessionCapability                                  `json:"sessionCapabilities,omitzero"`
		SessionID                              *string                                              `json:"sessionId,omitempty"`
		ShellInitProfile                       *string                                              `json:"shellInitProfile,omitempty"`
		ShellProcessFlags                      []string                                             `json:"shellProcessFlags,omitzero"`
		SkillDirectories                       []string                                             `json:"skillDirectories,omitzero"`
		SkipCustomInstructions                 *bool                                                `json:"skipCustomInstructions,omitempty"`
		TrajectoryFile                         *string                                              `json:"trajectoryFile,omitempty"`
		WorkingDirectory                       *string                                              `json:"workingDirectory,omitempty"`
		WorkingDirectoryContext                *SessionContext                                      `json:"workingDirectoryContext,omitempty"`
	}
	var raw rawSessionOpenOptions
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.AdditionalContentExclusionPolicies = raw.AdditionalContentExclusionPolicies
	r.AgentContext = raw.AgentContext
	r.AskUserDisabled = raw.AskUserDisabled
	if raw.AuthInfo != nil {
		value, err := unmarshalAuthInfo(raw.AuthInfo)
		if err != nil {
			return err
		}
		r.AuthInfo = value
	}
	r.AvailableTools = raw.AvailableTools
	r.ClientKind = raw.ClientKind
	r.ClientName = raw.ClientName
	r.CoauthorEnabled = raw.CoauthorEnabled
	r.ConfigDir = raw.ConfigDir
	r.ContinueOnAutoMode = raw.ContinueOnAutoMode
	r.CopilotURL = raw.CopilotURL
	r.CustomAgentsLocalOnly = raw.CustomAgentsLocalOnly
	r.DetachedFromSpawningParentEngagementID = raw.DetachedFromSpawningParentEngagementID
	r.DetachedFromSpawningParentSessionID = raw.DetachedFromSpawningParentSessionID
	r.DisabledInstructionSources = raw.DisabledInstructionSources
	r.DisabledSkills = raw.DisabledSkills
	r.EnableOnDemandInstructionDiscovery = raw.EnableOnDemandInstructionDiscovery
	r.EnableScriptSafety = raw.EnableScriptSafety
	r.EnableStreaming = raw.EnableStreaming
	r.EnvValueMode = raw.EnvValueMode
	r.EventsLogDirectory = raw.EventsLogDirectory
	r.ExcludedTools = raw.ExcludedTools
	r.ExpAssignments = raw.ExpAssignments
	r.FeatureFlags = raw.FeatureFlags
	r.InstalledPlugins = raw.InstalledPlugins
	r.IntegrationID = raw.IntegrationID
	r.IsExperimentalMode = raw.IsExperimentalMode
	r.LogInteractiveShells = raw.LogInteractiveShells
	r.LspClientName = raw.LspClientName
	r.MaxInlineBinaryBytes = raw.MaxInlineBinaryBytes
	r.Memory = raw.Memory
	r.Model = raw.Model
	r.ModelCapabilitiesOverrides = raw.ModelCapabilitiesOverrides
	r.Models = raw.Models
	r.Name = raw.Name
	r.Provider = raw.Provider
	r.Providers = raw.Providers
	r.ReasoningEffort = raw.ReasoningEffort
	r.ReasoningSummary = raw.ReasoningSummary
	r.RemoteDefaultedOn = raw.RemoteDefaultedOn
	r.RemoteExporting = raw.RemoteExporting
	r.RemoteSteerable = raw.RemoteSteerable
	r.RunningInInteractiveMode = raw.RunningInInteractiveMode
	r.SandboxConfig = raw.SandboxConfig
	r.SessionCapabilities = raw.SessionCapabilities
	r.SessionID = raw.SessionID
	r.ShellInitProfile = raw.ShellInitProfile
	r.ShellProcessFlags = raw.ShellProcessFlags
	r.SkillDirectories = raw.SkillDirectories
	r.SkipCustomInstructions = raw.SkipCustomInstructions
	r.TrajectoryFile = raw.TrajectoryFile
	r.WorkingDirectory = raw.WorkingDirectory
	r.WorkingDirectoryContext = raw.WorkingDirectoryContext
	return nil
}

func unmarshalSessionOpenParams(data []byte) (SessionOpenParams, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind SessionOpenParamsKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case SessionOpenParamsKindAttach:
		var d SessionsOpenAttach
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindCloud:
		var d SessionsOpenCloud
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindCreate:
		var d SessionsOpenCreate
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindHandoff:
		var d SessionsOpenHandoff
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindRemote:
		var d SessionsOpenRemote
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindResume:
		var d SessionsOpenResume
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SessionOpenParamsKindResumeLast:
		var d SessionsOpenResumeLast
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawSessionOpenParamsData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawSessionOpenParamsData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r SessionsOpenAttach) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenAttach
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenCloud) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenCloud
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenCreate) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenCreate
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenHandoff) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenHandoff
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenRemote) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenRemote
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenResume) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenResume
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SessionsOpenResumeLast) MarshalJSON() ([]byte, error) {
	type alias SessionsOpenResumeLast
	return json.Marshal(struct {
		Kind SessionOpenParamsKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r *SessionSetCredentialsParams) UnmarshalJSON(data []byte) error {
	type rawSessionSetCredentialsParams struct {
		Credentials json.RawMessage `json:"credentials,omitempty"`
	}
	var raw rawSessionSetCredentialsParams
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Credentials != nil {
		value, err := unmarshalAuthInfo(raw.Credentials)
		if err != nil {
			return err
		}
		r.Credentials = value
	}
	return nil
}

func unmarshalSlashCommandInvocationResult(data []byte) (SlashCommandInvocationResult, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Kind {
	case SlashCommandInvocationResultKindAgentPrompt:
		var d SlashCommandAgentPromptResult
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SlashCommandInvocationResultKindCompleted:
		var d SlashCommandCompletedResult
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SlashCommandInvocationResultKindSelectSubcommand:
		var d SlashCommandSelectSubcommandResult
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case SlashCommandInvocationResultKindText:
		var d SlashCommandTextResult
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawSlashCommandInvocationResultData{Discriminator: raw.Kind, Raw: data}, nil
	}
}

func (r RawSlashCommandInvocationResultData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
	}{
		Kind: r.Discriminator,
	})
}

func (r SlashCommandAgentPromptResult) MarshalJSON() ([]byte, error) {
	type alias SlashCommandAgentPromptResult
	return json.Marshal(struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SlashCommandCompletedResult) MarshalJSON() ([]byte, error) {
	type alias SlashCommandCompletedResult
	return json.Marshal(struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SlashCommandSelectSubcommandResult) MarshalJSON() ([]byte, error) {
	type alias SlashCommandSelectSubcommandResult
	return json.Marshal(struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func (r SlashCommandTextResult) MarshalJSON() ([]byte, error) {
	type alias SlashCommandTextResult
	return json.Marshal(struct {
		Kind SlashCommandInvocationResultKind `json:"kind"`
		alias
	}{
		Kind:  r.Kind(),
		alias: alias(r),
	})
}

func unmarshalTaskInfo(data []byte) (TaskInfo, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type TaskInfoType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case TaskInfoTypeAgent:
		var d TaskAgentInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case TaskInfoTypeShell:
		var d TaskShellInfo
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawTaskInfoData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawTaskInfoData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type TaskInfoType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r TaskAgentInfo) MarshalJSON() ([]byte, error) {
	type alias TaskAgentInfo
	return json.Marshal(struct {
		Type TaskInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r TaskShellInfo) MarshalJSON() ([]byte, error) {
	type alias TaskShellInfo
	return json.Marshal(struct {
		Type TaskInfoType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r *TaskList) UnmarshalJSON(data []byte) error {
	type rawTaskList struct {
		Tasks []json.RawMessage `json:"tasks"`
	}
	var raw rawTaskList
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Tasks != nil {
		r.Tasks = make([]TaskInfo, 0, len(raw.Tasks))
		for _, rawItem := range raw.Tasks {
			value, err := unmarshalTaskInfo(rawItem)
			if err != nil {
				return err
			}
			r.Tasks = append(r.Tasks, value)
		}
	}
	return nil
}

func unmarshalTaskProgress(data []byte) (TaskProgress, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type TaskProgressType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case TaskProgressTypeAgent:
		var d TaskAgentProgress
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case TaskProgressTypeShell:
		var d TaskShellProgress
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	default:
		return &RawTaskProgressData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawTaskProgressData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type TaskProgressType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r TaskAgentProgress) MarshalJSON() ([]byte, error) {
	type alias TaskAgentProgress
	return json.Marshal(struct {
		Type TaskProgressType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r TaskShellProgress) MarshalJSON() ([]byte, error) {
	type alias TaskShellProgress
	return json.Marshal(struct {
		Type TaskProgressType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r *TasksGetCurrentPromotableResult) UnmarshalJSON(data []byte) error {
	type rawTasksGetCurrentPromotableResult struct {
		Task json.RawMessage `json:"task,omitempty"`
	}
	var raw rawTasksGetCurrentPromotableResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Task != nil {
		value, err := unmarshalTaskInfo(raw.Task)
		if err != nil {
			return err
		}
		r.Task = value
	}
	return nil
}

func (r *TasksGetProgressResult) UnmarshalJSON(data []byte) error {
	type rawTasksGetProgressResult struct {
		Progress json.RawMessage `json:"progress,omitempty"`
	}
	var raw rawTasksGetProgressResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Progress != nil {
		value, err := unmarshalTaskProgress(raw.Progress)
		if err != nil {
			return err
		}
		r.Progress = value
	}
	return nil
}

func (r *TasksPromoteCurrentToBackgroundResult) UnmarshalJSON(data []byte) error {
	type rawTasksPromoteCurrentToBackgroundResult struct {
		Task json.RawMessage `json:"task,omitempty"`
	}
	var raw rawTasksPromoteCurrentToBackgroundResult
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Task != nil {
		value, err := unmarshalTaskInfo(raw.Task)
		if err != nil {
			return err
		}
		r.Task = value
	}
	return nil
}

func unmarshalUIElicitationFieldValue(data []byte) (UIElicitationFieldValue, error) {
	if string(data) == "null" {
		return nil, nil
	}
	{
		var value string
		if err := json.Unmarshal(data, &value); err == nil {
			return UIElicitationStringValue(value), nil
		}
	}
	{
		var value float64
		if err := json.Unmarshal(data, &value); err == nil {
			return UIElicitationNumberValue(value), nil
		}
	}
	{
		var value bool
		if err := json.Unmarshal(data, &value); err == nil {
			return UIElicitationBooleanValue(value), nil
		}
	}
	{
		var value []string
		if err := json.Unmarshal(data, &value); err == nil {
			return UIElicitationStringArrayValue(value), nil
		}
	}
	return nil, errors.New("data did not match any union variant for UIElicitationFieldValue")
}

func matchesUIElicitationArrayAnyOfField(data []byte) bool {
	var rawGroup0 struct {
		Items json.RawMessage `json:"items"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Items == nil {
		return false
	}
	var rawGroup0Items struct {
		AnyOf json.RawMessage `json:"anyOf"`
		Enum  json.RawMessage `json:"enum"`
		Type  json.RawMessage `json:"type"`
	}
	if err := json.Unmarshal(rawGroup0.Items, &rawGroup0Items); err != nil {
		return false
	}
	if rawGroup0Items.AnyOf == nil {
		return false
	}
	if rawGroup0Items.Enum != nil {
		return false
	}
	return rawGroup0Items.Type == nil
}

func matchesUIElicitationArrayEnumField(data []byte) bool {
	var rawGroup0 struct {
		Items json.RawMessage `json:"items"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Items == nil {
		return false
	}
	var rawGroup0Items struct {
		AnyOf json.RawMessage `json:"anyOf"`
		Enum  json.RawMessage `json:"enum"`
		Type  json.RawMessage `json:"type"`
	}
	if err := json.Unmarshal(rawGroup0.Items, &rawGroup0Items); err != nil {
		return false
	}
	if rawGroup0Items.Enum == nil {
		return false
	}
	if rawGroup0Items.Type == nil {
		return false
	}
	var rawGroup0String string
	if err := json.Unmarshal(rawGroup0Items.Type, &rawGroup0String); err != nil {
		return false
	}
	switch rawGroup0String {
	case "string":
	default:
		return false
	}
	return rawGroup0Items.AnyOf == nil
}

func matchesUIElicitationSchemaPropertyString(data []byte) bool {
	var rawGroup0 struct {
		Enum  json.RawMessage `json:"enum"`
		OneOf json.RawMessage `json:"oneOf"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Enum != nil {
		return false
	}
	return rawGroup0.OneOf == nil
}

func matchesUIElicitationStringEnumField(data []byte) bool {
	var rawGroup0 struct {
		Enum  json.RawMessage `json:"enum"`
		OneOf json.RawMessage `json:"oneOf"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.Enum == nil {
		return false
	}
	return rawGroup0.OneOf == nil
}

func matchesUIElicitationStringOneOfField(data []byte) bool {
	var rawGroup0 struct {
		Enum  json.RawMessage `json:"enum"`
		OneOf json.RawMessage `json:"oneOf"`
	}
	if err := json.Unmarshal(data, &rawGroup0); err != nil {
		return false
	}
	if rawGroup0.OneOf == nil {
		return false
	}
	return rawGroup0.Enum == nil
}

func unmarshalUIElicitationSchemaProperty(data []byte) (UIElicitationSchemaProperty, error) {
	if string(data) == "null" {
		return nil, nil
	}
	type rawUnion struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
	}
	var raw rawUnion
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	switch raw.Type {
	case UIElicitationSchemaPropertyTypeArray:
		if matchesUIElicitationArrayAnyOfField(data) {
			var d UIElicitationArrayAnyOfField
			if err := json.Unmarshal(data, &d); err != nil {
				return nil, err
			}
			return &d, nil
		}
		if matchesUIElicitationArrayEnumField(data) {
			var d UIElicitationArrayEnumField
			if err := json.Unmarshal(data, &d); err != nil {
				return nil, err
			}
			return &d, nil
		}
		return &RawUIElicitationSchemaPropertyData{Discriminator: raw.Type, Raw: data}, nil
	case UIElicitationSchemaPropertyTypeBoolean:
		var d UIElicitationSchemaPropertyBoolean
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UIElicitationSchemaPropertyTypeInteger:
		var d UIElicitationSchemaPropertyNumber
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UIElicitationSchemaPropertyTypeNumber:
		var d UIElicitationSchemaPropertyNumber
		if err := json.Unmarshal(data, &d); err != nil {
			return nil, err
		}
		return &d, nil
	case UIElicitationSchemaPropertyTypeString:
		if matchesUIElicitationSchemaPropertyString(data) {
			var d UIElicitationSchemaPropertyString
			if err := json.Unmarshal(data, &d); err != nil {
				return nil, err
			}
			return &d, nil
		}
		if matchesUIElicitationStringEnumField(data) {
			var d UIElicitationStringEnumField
			if err := json.Unmarshal(data, &d); err != nil {
				return nil, err
			}
			return &d, nil
		}
		if matchesUIElicitationStringOneOfField(data) {
			var d UIElicitationStringOneOfField
			if err := json.Unmarshal(data, &d); err != nil {
				return nil, err
			}
			return &d, nil
		}
		return &RawUIElicitationSchemaPropertyData{Discriminator: raw.Type, Raw: data}, nil
	default:
		return &RawUIElicitationSchemaPropertyData{Discriminator: raw.Type, Raw: data}, nil
	}
}

func (r RawUIElicitationSchemaPropertyData) MarshalJSON() ([]byte, error) {
	if r.Raw != nil {
		return r.Raw, nil
	}
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
	}{
		Type: r.Discriminator,
	})
}

func (r UIElicitationArrayAnyOfField) MarshalJSON() ([]byte, error) {
	type alias UIElicitationArrayAnyOfField
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationArrayEnumField) MarshalJSON() ([]byte, error) {
	type alias UIElicitationArrayEnumField
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationSchemaPropertyBoolean) MarshalJSON() ([]byte, error) {
	type alias UIElicitationSchemaPropertyBoolean
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationSchemaPropertyNumber) MarshalJSON() ([]byte, error) {
	type alias UIElicitationSchemaPropertyNumber
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationSchemaPropertyString) MarshalJSON() ([]byte, error) {
	type alias UIElicitationSchemaPropertyString
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationStringEnumField) MarshalJSON() ([]byte, error) {
	type alias UIElicitationStringEnumField
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r UIElicitationStringOneOfField) MarshalJSON() ([]byte, error) {
	type alias UIElicitationStringOneOfField
	return json.Marshal(struct {
		Type UIElicitationSchemaPropertyType `json:"type"`
		alias
	}{
		Type:  r.Type(),
		alias: alias(r),
	})
}

func (r *UIElicitationSchema) UnmarshalJSON(data []byte) error {
	type rawUIElicitationSchema struct {
		Properties map[string]json.RawMessage `json:"properties"`
		Required   []string                   `json:"required,omitzero"`
		Type       UIElicitationSchemaType    `json:"type"`
	}
	var raw rawUIElicitationSchema
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if raw.Properties != nil {
		r.Properties = make(map[string]UIElicitationSchemaProperty, len(raw.Properties))
		for key, rawValue := range raw.Properties {
			value, err := unmarshalUIElicitationSchemaProperty(rawValue)
			if err != nil {
				return err
			}
			r.Properties[key] = value
		}
	}
	r.Required = raw.Required
	r.Type = raw.Type
	return nil
}

func (r *UIElicitationResponse) UnmarshalJSON(data []byte) error {
	type rawUIElicitationResponse struct {
		Action  UIElicitationResponseAction `json:"action"`
		Content map[string]json.RawMessage  `json:"content,omitzero"`
	}
	var raw rawUIElicitationResponse
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	r.Action = raw.Action
	if raw.Content != nil {
		r.Content = make(map[string]UIElicitationFieldValue, len(raw.Content))
		for key, rawValue := range raw.Content {
			value, err := unmarshalUIElicitationFieldValue(rawValue)
			if err != nil {
				return err
			}
			r.Content[key] = value
		}
	}
	return nil
}
