"""
Copilot SDK - Python Client for GitHub Copilot CLI

JSON-RPC based SDK for programmatic control of GitHub Copilot CLI
"""

from .client import CopilotClient
from .session import CopilotSession
from .tools import define_tool
from .types import (
    Attachment,
    AzureProviderOptions,
    BlobAttachment,
    ConnectionState,
    CustomAgentConfig,
    DirectoryAttachment,
    ExternalServerConfig,
    FileAttachment,
    GetAuthStatusResponse,
    GetStatusResponse,
    MCPLocalServerConfig,
    MCPRemoteServerConfig,
    MCPServerConfig,
    ModelBilling,
    ModelCapabilities,
    ModelInfo,
    ModelPolicy,
    PermissionHandler,
    PermissionRequest,
    PermissionRequestResult,
    PingResponse,
    ProviderConfig,
    ResumeSessionConfig,
    SelectionAttachment,
    SessionConfig,
    SessionContext,
    SessionEvent,
    SessionListFilter,
    SessionMetadata,
    StopError,
    SubprocessConfig,
    TelemetryConfig,
    Tool,
    ToolHandler,
    ToolInvocation,
    ToolResult,
)

__version__ = "0.1.0"

__all__ = [
    "Attachment",
    "AzureProviderOptions",
    "BlobAttachment",
    "CopilotClient",
    "CopilotSession",
    "ConnectionState",
    "CustomAgentConfig",
    "DirectoryAttachment",
    "ExternalServerConfig",
    "FileAttachment",
    "GetAuthStatusResponse",
    "GetStatusResponse",
    "MCPLocalServerConfig",
    "MCPRemoteServerConfig",
    "MCPServerConfig",
    "ModelBilling",
    "ModelCapabilities",
    "ModelInfo",
    "ModelPolicy",
    "PermissionHandler",
    "PermissionRequest",
    "PermissionRequestResult",
    "PingResponse",
    "ProviderConfig",
    "ResumeSessionConfig",
    "SelectionAttachment",
    "SessionConfig",
    "SessionContext",
    "SessionEvent",
    "SessionListFilter",
    "SessionMetadata",
    "StopError",
    "SubprocessConfig",
    "TelemetryConfig",
    "Tool",
    "ToolHandler",
    "ToolInvocation",
    "ToolResult",
    "define_tool",
]
