"""
Copilot SDK - Python Client for GitHub Copilot CLI

JSON-RPC based SDK for programmatic control of GitHub Copilot CLI
"""

from .client import (
    CloudSessionOptions,
    CloudSessionRepository,
    CopilotClient,
    ExternalServerConfig,
    ModelCapabilitiesOverride,
    ModelLimitsOverride,
    ModelSupportsOverride,
    ModelVisionLimitsOverride,
    RemoteSessionMode,
    SubprocessConfig,
)
from .session import (
    AutoModeSwitchHandler,
    AutoModeSwitchRequest,
    AutoModeSwitchResponse,
    CommandContext,
    CommandDefinition,
    CopilotSession,
    CreateSessionFsHandler,
    ElicitationContext,
    ElicitationHandler,
    ElicitationParams,
    ElicitationResult,
    ExitPlanModeHandler,
    ExitPlanModeRequest,
    ExitPlanModeResult,
    InputOptions,
    ProviderConfig,
    SessionCapabilities,
    SessionFsCapabilities,
    SessionFsConfig,
    SessionUiApi,
    SessionUiCapabilities,
)
from .session_fs_provider import (
    SessionFsFileInfo,
    SessionFsProvider,
    SessionFsSqliteProvider,
    SessionFsSqliteQueryResult,
    create_session_fs_adapter,
)
from .tools import (
    Tool,
    ToolBinaryResult,
    ToolInvocation,
    ToolResult,
    convert_mcp_call_tool_result,
    define_tool,
)

__version__ = "0.1.0"

__all__ = [
    "CommandContext",
    "AutoModeSwitchHandler",
    "AutoModeSwitchRequest",
    "AutoModeSwitchResponse",
    "CommandDefinition",
    "CloudSessionOptions",
    "CloudSessionRepository",
    "CopilotClient",
    "CopilotSession",
    "CreateSessionFsHandler",
    "ElicitationHandler",
    "ElicitationParams",
    "ElicitationContext",
    "ElicitationResult",
    "ExitPlanModeHandler",
    "ExitPlanModeRequest",
    "ExitPlanModeResult",
    "ExternalServerConfig",
    "InputOptions",
    "ModelCapabilitiesOverride",
    "ModelLimitsOverride",
    "ModelSupportsOverride",
    "ModelVisionLimitsOverride",
    "ProviderConfig",
    "RemoteSessionMode",
    "SessionCapabilities",
    "SessionFsCapabilities",
    "SessionFsConfig",
    "SessionFsFileInfo",
    "SessionFsProvider",
    "SessionFsSqliteProvider",
    "SessionFsSqliteQueryResult",
    "create_session_fs_adapter",
    "SessionUiApi",
    "SessionUiCapabilities",
    "SubprocessConfig",
    "Tool",
    "ToolBinaryResult",
    "ToolInvocation",
    "ToolResult",
    "convert_mcp_call_tool_result",
    "define_tool",
]
