# Code generated by update-protocol-version.ts. DO NOT EDIT.

"""
SDK Protocol Version for the Copilot SDK.

This must match the version expected by the copilot-agent-runtime server.
"""

SDK_PROTOCOL_VERSION = 3


def get_sdk_protocol_version() -> int:
    """
    Gets the SDK protocol version.

    Returns:
        The protocol version number
    """
    return SDK_PROTOCOL_VERSION
