// Code generated by update-protocol-version.ts. DO NOT EDIT.

//! The SDK protocol version. Must match the version expected by the
//! copilot-agent-runtime server.

/// The SDK protocol version.
pub const SDK_PROTOCOL_VERSION: u32 = 3;

/// Returns the SDK protocol version.
#[must_use]
pub const fn get_sdk_protocol_version() -> u32 {
    SDK_PROTOCOL_VERSION
}
