/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

// Code generated by update-protocol-version.ts. DO NOT EDIT.

/**
 * The SDK protocol version.
 * This must match the version expected by the copilot-agent-runtime server.
 */
export const SDK_PROTOCOL_VERSION = 3;

/**
 * Gets the SDK protocol version.
 * @returns The protocol version number
 */
export function getSdkProtocolVersion(): number {
    return SDK_PROTOCOL_VERSION;
}
