// Code generated by update-protocol-version.ts. DO NOT EDIT.

namespace GitHub.Copilot.SDK;

/// <summary>
/// Provides the SDK protocol version.
/// This must match the version expected by the copilot-agent-runtime server.
/// </summary>
internal static class SdkProtocolVersion
{
    /// <summary>
    /// The SDK protocol version.
    /// </summary>
    private const int Version = 3;

    /// <summary>
    /// Gets the SDK protocol version.
    /// </summary>
    public static int GetVersion() => Version;
}
