// AUTO-GENERATED FILE - DO NOT EDIT
//
// Generated from: @github/copilot/session-events.schema.json
// Generated by: scripts/generate-session-types.ts
// Generated at: 2026-02-06T20:38:23.463Z
//
// To update these types:
// 1. Update the schema in copilot-agent-runtime
// 2. Run: npm run generate:session-types

// Code generated from JSON Schema using quicktype. DO NOT EDIT.
// To parse and unparse this JSON data, add this code to your project and do:
//
//    sessionEvent, err := UnmarshalSessionEvent(bytes)
//    bytes, err = sessionEvent.Marshal()

package copilot

import "bytes"
import "errors"
import "time"

import "encoding/json"

func UnmarshalSessionEvent(data []byte) (SessionEvent, error) {
	var r SessionEvent
	err := json.Unmarshal(data, &r)
	return r, err
}

func (r *SessionEvent) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

type SessionEvent struct {
	Data      Data             `json:"data"`
	Ephemeral *bool            `json:"ephemeral,omitempty"`
	ID        string           `json:"id"`
	ParentID  *string          `json:"parentId"`
	Timestamp time.Time        `json:"timestamp"`
	Type      SessionEventType `json:"type"`
}

type Data struct {
	Context                         *ContextUnion            `json:"context"`
	CopilotVersion                  *string                  `json:"copilotVersion,omitempty"`
	Producer                        *string                  `json:"producer,omitempty"`
	SelectedModel                   *string                  `json:"selectedModel,omitempty"`
	SessionID                       *string                  `json:"sessionId,omitempty"`
	StartTime                       *time.Time               `json:"startTime,omitempty"`
	Version                         *float64                 `json:"version,omitempty"`
	EventCount                      *float64                 `json:"eventCount,omitempty"`
	ResumeTime                      *time.Time               `json:"resumeTime,omitempty"`
	ErrorType                       *string                  `json:"errorType,omitempty"`
	Message                         *string                  `json:"message,omitempty"`
	ProviderCallID                  *string                  `json:"providerCallId,omitempty"`
	Stack                           *string                  `json:"stack,omitempty"`
	StatusCode                      *int64                   `json:"statusCode,omitempty"`
	InfoType                        *string                  `json:"infoType,omitempty"`
	NewModel                        *string                  `json:"newModel,omitempty"`
	PreviousModel                   *string                  `json:"previousModel,omitempty"`
	HandoffTime                     *time.Time               `json:"handoffTime,omitempty"`
	RemoteSessionID                 *string                  `json:"remoteSessionId,omitempty"`
	Repository                      *Repository              `json:"repository,omitempty"`
	SourceType                      *SourceType              `json:"sourceType,omitempty"`
	Summary                         *string                  `json:"summary,omitempty"`
	MessagesRemovedDuringTruncation *float64                 `json:"messagesRemovedDuringTruncation,omitempty"`
	PerformedBy                     *string                  `json:"performedBy,omitempty"`
	PostTruncationMessagesLength    *float64                 `json:"postTruncationMessagesLength,omitempty"`
	PostTruncationTokensInMessages  *float64                 `json:"postTruncationTokensInMessages,omitempty"`
	PreTruncationMessagesLength     *float64                 `json:"preTruncationMessagesLength,omitempty"`
	PreTruncationTokensInMessages   *float64                 `json:"preTruncationTokensInMessages,omitempty"`
	TokenLimit                      *float64                 `json:"tokenLimit,omitempty"`
	TokensRemovedDuringTruncation   *float64                 `json:"tokensRemovedDuringTruncation,omitempty"`
	EventsRemoved                   *float64                 `json:"eventsRemoved,omitempty"`
	UpToEventID                     *string                  `json:"upToEventId,omitempty"`
	CodeChanges                     *CodeChanges             `json:"codeChanges,omitempty"`
	CurrentModel                    *string                  `json:"currentModel,omitempty"`
	ErrorReason                     *string                  `json:"errorReason,omitempty"`
	ModelMetrics                    map[string]ModelMetric   `json:"modelMetrics,omitempty"`
	SessionStartTime                *float64                 `json:"sessionStartTime,omitempty"`
	ShutdownType                    *ShutdownType            `json:"shutdownType,omitempty"`
	TotalAPIDurationMS              *float64                 `json:"totalApiDurationMs,omitempty"`
	TotalPremiumRequests            *float64                 `json:"totalPremiumRequests,omitempty"`
	CurrentTokens                   *float64                 `json:"currentTokens,omitempty"`
	MessagesLength                  *float64                 `json:"messagesLength,omitempty"`
	CheckpointNumber                *float64                 `json:"checkpointNumber,omitempty"`
	CheckpointPath                  *string                  `json:"checkpointPath,omitempty"`
	CompactionTokensUsed            *CompactionTokensUsed    `json:"compactionTokensUsed,omitempty"`
	Error                           *ErrorUnion              `json:"error"`
	MessagesRemoved                 *float64                 `json:"messagesRemoved,omitempty"`
	PostCompactionTokens            *float64                 `json:"postCompactionTokens,omitempty"`
	PreCompactionMessagesLength     *float64                 `json:"preCompactionMessagesLength,omitempty"`
	PreCompactionTokens             *float64                 `json:"preCompactionTokens,omitempty"`
	RequestID                       *string                  `json:"requestId,omitempty"`
	Success                         *bool                    `json:"success,omitempty"`
	SummaryContent                  *string                  `json:"summaryContent,omitempty"`
	TokensRemoved                   *float64                 `json:"tokensRemoved,omitempty"`
	Attachments                     []Attachment             `json:"attachments,omitempty"`
	Content                         *string                  `json:"content,omitempty"`
	Source                          *string                  `json:"source,omitempty"`
	TransformedContent              *string                  `json:"transformedContent,omitempty"`
	TurnID                          *string                  `json:"turnId,omitempty"`
	Intent                          *string                  `json:"intent,omitempty"`
	ReasoningID                     *string                  `json:"reasoningId,omitempty"`
	DeltaContent                    *string                  `json:"deltaContent,omitempty"`
	EncryptedContent                *string                  `json:"encryptedContent,omitempty"`
	MessageID                       *string                  `json:"messageId,omitempty"`
	ParentToolCallID                *string                  `json:"parentToolCallId,omitempty"`
	ReasoningOpaque                 *string                  `json:"reasoningOpaque,omitempty"`
	ReasoningText                   *string                  `json:"reasoningText,omitempty"`
	ToolRequests                    []ToolRequest            `json:"toolRequests,omitempty"`
	TotalResponseSizeBytes          *float64                 `json:"totalResponseSizeBytes,omitempty"`
	APICallID                       *string                  `json:"apiCallId,omitempty"`
	CacheReadTokens                 *float64                 `json:"cacheReadTokens,omitempty"`
	CacheWriteTokens                *float64                 `json:"cacheWriteTokens,omitempty"`
	Cost                            *float64                 `json:"cost,omitempty"`
	Duration                        *float64                 `json:"duration,omitempty"`
	Initiator                       *string                  `json:"initiator,omitempty"`
	InputTokens                     *float64                 `json:"inputTokens,omitempty"`
	Model                           *string                  `json:"model,omitempty"`
	OutputTokens                    *float64                 `json:"outputTokens,omitempty"`
	QuotaSnapshots                  map[string]QuotaSnapshot `json:"quotaSnapshots,omitempty"`
	Reason                          *string                  `json:"reason,omitempty"`
	Arguments                       interface{}              `json:"arguments"`
	ToolCallID                      *string                  `json:"toolCallId,omitempty"`
	ToolName                        *string                  `json:"toolName,omitempty"`
	MCPServerName                   *string                  `json:"mcpServerName,omitempty"`
	MCPToolName                     *string                  `json:"mcpToolName,omitempty"`
	PartialOutput                   *string                  `json:"partialOutput,omitempty"`
	ProgressMessage                 *string                  `json:"progressMessage,omitempty"`
	IsUserRequested                 *bool                    `json:"isUserRequested,omitempty"`
	Result                          *Result                  `json:"result,omitempty"`
	ToolTelemetry                   map[string]interface{}   `json:"toolTelemetry,omitempty"`
	AllowedTools                    []string                 `json:"allowedTools,omitempty"`
	Name                            *string                  `json:"name,omitempty"`
	Path                            *string                  `json:"path,omitempty"`
	AgentDescription                *string                  `json:"agentDescription,omitempty"`
	AgentDisplayName                *string                  `json:"agentDisplayName,omitempty"`
	AgentName                       *string                  `json:"agentName,omitempty"`
	Tools                           []string                 `json:"tools"`
	HookInvocationID                *string                  `json:"hookInvocationId,omitempty"`
	HookType                        *string                  `json:"hookType,omitempty"`
	Input                           interface{}              `json:"input"`
	Output                          interface{}              `json:"output"`
	Metadata                        *Metadata                `json:"metadata,omitempty"`
	Role                            *Role                    `json:"role,omitempty"`
}

type Attachment struct {
	DisplayName string          `json:"displayName"`
	Path        *string         `json:"path,omitempty"`
	Type        AttachmentType  `json:"type"`
	FilePath    *string         `json:"filePath,omitempty"`
	Selection   *SelectionClass `json:"selection,omitempty"`
	Text        *string         `json:"text,omitempty"`
}

type SelectionClass struct {
	End   End   `json:"end"`
	Start Start `json:"start"`
}

type End struct {
	Character float64 `json:"character"`
	Line      float64 `json:"line"`
}

type Start struct {
	Character float64 `json:"character"`
	Line      float64 `json:"line"`
}

type CodeChanges struct {
	FilesModified []string `json:"filesModified"`
	LinesAdded    float64  `json:"linesAdded"`
	LinesRemoved  float64  `json:"linesRemoved"`
}

type CompactionTokensUsed struct {
	CachedInput float64 `json:"cachedInput"`
	Input       float64 `json:"input"`
	Output      float64 `json:"output"`
}

type ContextClass struct {
	Branch     *string `json:"branch,omitempty"`
	Cwd        string  `json:"cwd"`
	GitRoot    *string `json:"gitRoot,omitempty"`
	Repository *string `json:"repository,omitempty"`
}

type ErrorClass struct {
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
	Stack   *string `json:"stack,omitempty"`
}

type Metadata struct {
	PromptVersion *string                `json:"promptVersion,omitempty"`
	Variables     map[string]interface{} `json:"variables,omitempty"`
}

type ModelMetric struct {
	Requests Requests `json:"requests"`
	Usage    Usage    `json:"usage"`
}

type Requests struct {
	Cost  float64 `json:"cost"`
	Count float64 `json:"count"`
}

type Usage struct {
	CacheReadTokens  float64 `json:"cacheReadTokens"`
	CacheWriteTokens float64 `json:"cacheWriteTokens"`
	InputTokens      float64 `json:"inputTokens"`
	OutputTokens     float64 `json:"outputTokens"`
}

type QuotaSnapshot struct {
	EntitlementRequests              float64    `json:"entitlementRequests"`
	IsUnlimitedEntitlement           bool       `json:"isUnlimitedEntitlement"`
	Overage                          float64    `json:"overage"`
	OverageAllowedWithExhaustedQuota bool       `json:"overageAllowedWithExhaustedQuota"`
	RemainingPercentage              float64    `json:"remainingPercentage"`
	ResetDate                        *time.Time `json:"resetDate,omitempty"`
	UsageAllowedWithExhaustedQuota   bool       `json:"usageAllowedWithExhaustedQuota"`
	UsedRequests                     float64    `json:"usedRequests"`
}

type Repository struct {
	Branch *string `json:"branch,omitempty"`
	Name   string  `json:"name"`
	Owner  string  `json:"owner"`
}

type Result struct {
	Content         string  `json:"content"`
	DetailedContent *string `json:"detailedContent,omitempty"`
}

type ToolRequest struct {
	Arguments  interface{}      `json:"arguments"`
	Name       string           `json:"name"`
	ToolCallID string           `json:"toolCallId"`
	Type       *ToolRequestType `json:"type,omitempty"`
}

type AttachmentType string

const (
	Directory AttachmentType = "directory"
	File      AttachmentType = "file"
	Selection AttachmentType = "selection"
)

type Role string

const (
	Developer Role = "developer"
	System    Role = "system"
)

type ShutdownType string

const (
	Error   ShutdownType = "error"
	Routine ShutdownType = "routine"
)

type SourceType string

const (
	Local  SourceType = "local"
	Remote SourceType = "remote"
)

type ToolRequestType string

const (
	Custom   ToolRequestType = "custom"
	Function ToolRequestType = "function"
)

type SessionEventType string

const (
	Abort                      SessionEventType = "abort"
	AssistantIntent            SessionEventType = "assistant.intent"
	AssistantMessage           SessionEventType = "assistant.message"
	AssistantMessageDelta      SessionEventType = "assistant.message_delta"
	AssistantReasoning         SessionEventType = "assistant.reasoning"
	AssistantReasoningDelta    SessionEventType = "assistant.reasoning_delta"
	AssistantTurnEnd           SessionEventType = "assistant.turn_end"
	AssistantTurnStart         SessionEventType = "assistant.turn_start"
	AssistantUsage             SessionEventType = "assistant.usage"
	HookEnd                    SessionEventType = "hook.end"
	HookStart                  SessionEventType = "hook.start"
	PendingMessagesModified    SessionEventType = "pending_messages.modified"
	SessionCompactionComplete  SessionEventType = "session.compaction_complete"
	SessionCompactionStart     SessionEventType = "session.compaction_start"
	SessionError               SessionEventType = "session.error"
	SessionHandoff             SessionEventType = "session.handoff"
	SessionIdle                SessionEventType = "session.idle"
	SessionInfo                SessionEventType = "session.info"
	SessionModelChange         SessionEventType = "session.model_change"
	SessionResume              SessionEventType = "session.resume"
	SessionShutdown            SessionEventType = "session.shutdown"
	SessionSnapshotRewind      SessionEventType = "session.snapshot_rewind"
	SessionStart               SessionEventType = "session.start"
	SessionTruncation          SessionEventType = "session.truncation"
	SessionUsageInfo           SessionEventType = "session.usage_info"
	SkillInvoked               SessionEventType = "skill.invoked"
	SubagentCompleted          SessionEventType = "subagent.completed"
	SubagentFailed             SessionEventType = "subagent.failed"
	SubagentSelected           SessionEventType = "subagent.selected"
	SubagentStarted            SessionEventType = "subagent.started"
	SystemMessage              SessionEventType = "system.message"
	ToolExecutionComplete      SessionEventType = "tool.execution_complete"
	ToolExecutionPartialResult SessionEventType = "tool.execution_partial_result"
	ToolExecutionProgress      SessionEventType = "tool.execution_progress"
	ToolExecutionStart         SessionEventType = "tool.execution_start"
	ToolUserRequested          SessionEventType = "tool.user_requested"
	UserMessage                SessionEventType = "user.message"
)

type ContextUnion struct {
	ContextClass *ContextClass
	String       *string
}

func (x *ContextUnion) UnmarshalJSON(data []byte) error {
	x.ContextClass = nil
	var c ContextClass
	object, err := unmarshalUnion(data, nil, nil, nil, &x.String, false, nil, true, &c, false, nil, false, nil, false)
	if err != nil {
		return err
	}
	if object {
		x.ContextClass = &c
	}
	return nil
}

func (x *ContextUnion) MarshalJSON() ([]byte, error) {
	return marshalUnion(nil, nil, nil, x.String, false, nil, x.ContextClass != nil, x.ContextClass, false, nil, false, nil, false)
}

type ErrorUnion struct {
	ErrorClass *ErrorClass
	String     *string
}

func (x *ErrorUnion) UnmarshalJSON(data []byte) error {
	x.ErrorClass = nil
	var c ErrorClass
	object, err := unmarshalUnion(data, nil, nil, nil, &x.String, false, nil, true, &c, false, nil, false, nil, false)
	if err != nil {
		return err
	}
	if object {
		x.ErrorClass = &c
	}
	return nil
}

func (x *ErrorUnion) MarshalJSON() ([]byte, error) {
	return marshalUnion(nil, nil, nil, x.String, false, nil, x.ErrorClass != nil, x.ErrorClass, false, nil, false, nil, false)
}

func unmarshalUnion(data []byte, pi **int64, pf **float64, pb **bool, ps **string, haveArray bool, pa interface{}, haveObject bool, pc interface{}, haveMap bool, pm interface{}, haveEnum bool, pe interface{}, nullable bool) (bool, error) {
	if pi != nil {
		*pi = nil
	}
	if pf != nil {
		*pf = nil
	}
	if pb != nil {
		*pb = nil
	}
	if ps != nil {
		*ps = nil
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	tok, err := dec.Token()
	if err != nil {
		return false, err
	}

	switch v := tok.(type) {
	case json.Number:
		if pi != nil {
			i, err := v.Int64()
			if err == nil {
				*pi = &i
				return false, nil
			}
		}
		if pf != nil {
			f, err := v.Float64()
			if err == nil {
				*pf = &f
				return false, nil
			}
			return false, errors.New("Unparsable number")
		}
		return false, errors.New("Union does not contain number")
	case float64:
		return false, errors.New("Decoder should not return float64")
	case bool:
		if pb != nil {
			*pb = &v
			return false, nil
		}
		return false, errors.New("Union does not contain bool")
	case string:
		if haveEnum {
			return false, json.Unmarshal(data, pe)
		}
		if ps != nil {
			*ps = &v
			return false, nil
		}
		return false, errors.New("Union does not contain string")
	case nil:
		if nullable {
			return false, nil
		}
		return false, errors.New("Union does not contain null")
	case json.Delim:
		if v == '{' {
			if haveObject {
				return true, json.Unmarshal(data, pc)
			}
			if haveMap {
				return false, json.Unmarshal(data, pm)
			}
			return false, errors.New("Union does not contain object")
		}
		if v == '[' {
			if haveArray {
				return false, json.Unmarshal(data, pa)
			}
			return false, errors.New("Union does not contain array")
		}
		return false, errors.New("Cannot handle delimiter")
	}
	return false, errors.New("Cannot unmarshal union")
}

func marshalUnion(pi *int64, pf *float64, pb *bool, ps *string, haveArray bool, pa interface{}, haveObject bool, pc interface{}, haveMap bool, pm interface{}, haveEnum bool, pe interface{}, nullable bool) ([]byte, error) {
	if pi != nil {
		return json.Marshal(*pi)
	}
	if pf != nil {
		return json.Marshal(*pf)
	}
	if pb != nil {
		return json.Marshal(*pb)
	}
	if ps != nil {
		return json.Marshal(*ps)
	}
	if haveArray {
		return json.Marshal(pa)
	}
	if haveObject {
		return json.Marshal(pc)
	}
	if haveMap {
		return json.Marshal(pm)
	}
	if haveEnum {
		return json.Marshal(pe)
	}
	if nullable {
		return json.Marshal(nil)
	}
	return nil, errors.New("Union must not be null")
}
