// Code generated by update-protocol-version.ts. DO NOT EDIT.

package copilot

// SDKProtocolVersion is the SDK protocol version.
// This must match the version expected by the copilot-agent-runtime server.
const SDKProtocolVersion = 3

// GetSDKProtocolVersion returns the SDK protocol version.
func GetSDKProtocolVersion() int {
	return SDKProtocolVersion
}
