// Code generated by update-protocol-version.ts. DO NOT EDIT.

package copilot

// SdkProtocolVersion is the SDK protocol version.
// This must match the version expected by the copilot-agent-runtime server.
const SdkProtocolVersion = 3

// GetSdkProtocolVersion returns the SDK protocol version.
func GetSdkProtocolVersion() int {
	return SdkProtocolVersion
}
